version: "3.7"

services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.2
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      LIMIT_RESOURCES: "true"
      CLUSTER_HOSTNAME: "weaviate"
      ENABLE_CLUSTER: "false"
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: "text2vec-ollama,generative-ollama"
      TEXT2VEC_OLLAMA_API_ENDPOINT: "http://host.docker.internal:11434"
      TEXT2VEC_OLLAMA_MODEL: "nomic-embed-text"
      GENERATIVE_OLLAMA_API_ENDPOINT: "http://host.docker.internal:11434"
      GENERATIVE_OLLAMA_MODEL: "llama3.2"
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data: